### ISSUE TITLE
The self-host build boots to a 500 on every route

### ISSUE THREAD

**Issue by mahmutefedara** [covan-ai/covan#101]
`main` builds cleanly and then serves nothing. Every SSR route returns 500 with:

```
TypeError: __exportAll is not a function
    at .output/server/_ssr/server-*.mjs:1630:38
    at ModuleJob.run (node:internal/modules/esm/module_job:569:25)
```

The page a visitor gets is the "This page didn't load" card, on `/`, `/privacy`, `/terms` — everything.

### Who this hits

Anyone running the open build: `Dockerfile.web` and the published `ghcr.io/covan-ai/covan-web` image both build this Node server. **covan.app is not affected** — it deploys with `NITRO_PRESET=cloudflare-module`, a different artifact, and I checked five routes on it just now, all 200.

### Reproducing

```
bun install
VITE_SUPABASE_URL=... VITE_SUPABASE_ANON_KEY=... VITE_API_URL=... bun run build
node .output/server/index.mjs
curl -o /dev/null -w '%{http_code}\n' http://localhost:3000/privacy
```

A clean `rm -rf .output .tanstack` first makes no difference.

### When it broke

Bisected to a seven-commit window:

| Commit | Result |
| --- | --- |
| `b449e97` (#91 merge, 09:22) | **200** |
| `ddbc3a6` (#100 merge, 10:03) | **500** |
| `d1accd3` (#97 merge, current main) | **500** |

So it arrived with one of #93, #94, #95, #96, #98, #99 or #100. I stopped there rather than bisect the rest — whoever owns those has the context to spot it faster than another four builds would find it.

### Why nothing caught it

CI runs `tsc`, `eslint`, unit tests and the RLS suite. **None of them boots the built server**, and the build itself exits 0 — the failure is at module load, inside the bundle, on the first request. Worth considering a smoke step that starts `.output/server/index.mjs` and curls one route; it is the only check that would have gone red here, and it is the check the container healthcheck already gestures at without actually exercising (a healthcheck that fetches the document passes on a page whose scripts never load — see the note in `scripts/web-runtime-config.mjs`).

**Comment by mahmutefedara** [comment]
Still reproduces on current `main` (`2d33cf6`), eight days on. Same error, same blast radius:

```
/          500
/privacy   500
/terms     500

TypeError: __exportAll is not a function
    at async Object.fetch (.output/server/_ssr/ssr.mjs:80:56)
```

Built with `bun run build` on a clean tree and served with `node .output/server/index.mjs`. Nothing in this repo's font/SEO work touched it either way — noting that only because that work rebuilt `.output` several times today and the failure is identical before and after.

covan.app remains unaffected, as the issue says: it deploys `NITRO_PRESET=cloudflare-module`, a different artifact. Checked `/`, `/blog`, `/docs` and `/privacy` on it just now, all 200.

So the split is still exactly as described — the hosted build is fine and the build every self-hoster runs is dead.

**Comment by mahmutefedara** [comment]
Root cause, from the emitted bundle rather than from bisecting: **a circular import between two chunks**, and the cycle's back-edge is what makes `__exportAll` unavailable at the moment it is called.

Built with `NITRO_PRESET=node-server` — the preset `Dockerfile.web` sets, so this is the configuration self-hosters actually run, not the default one the repro steps above use. Both fail identically.

Two chunks are emitted whose names differ only by a `2`:

| file | size | exports `n` | exports `t` |
| --- | --- | --- | --- |
| `_ssr/server-DRp9LhFb.mjs` | 495 B | `__exportAll` | `server_exports` |
| `_ssr/server-DRp9LhFb2.mjs` | 61 KB | `createServerEntry` | `createMiddleware` |

The small one is the Rolldown runtime shim, inlined out of `node_modules/.nitro/vite/services/ssr/assets/rolldown-runtime-D7D4PA-g.js`. In full:

```js
import { i as server_exports } from "./server-DRp9LhFb2.mjs";
var __defProp = Object.defineProperty;
var __exportAll = (all, no_symbols) => { /* … */ };
export { __exportAll as n, server_exports as t };
```

And the 61 KB chunk opens with:

```js
import { n as __exportAll } from "./server-DRp9LhFb.mjs";
```

So each imports from the other. `__exportAll` is defined, and the import specifiers are correct — but it is a `var` initialised during module evaluation, and the cycle means the large chunk is evaluated first and reaches it while it is still `undefined`. Hence `TypeError: __exportAll is not a function` rather than a resolution error, which is why grepping for a missing file finds nothing.

The back-edge is the shim re-exporting `server_exports`, which it only does because the chunker put the runtime helper and that re-export in the same 495-byte chunk. Anything that stops those two travelling together should break the cycle — a `manualChunks` rule pinning the rolldown runtime to its own chunk is the smallest lever; a vite/rolldown bump may also move it, since the chunk naming (`…2.mjs`) suggests a hash collision being disambiguated after the graph was decided.

**Unrelated but worth separating, because the names collide:** this is the bundler's `__exportAll` helper, nothing to do with the workspace export feature in `worker/src/lib/export/`. That feature is fine.

Verified today on `main` (`2d33cf6`), clean tree, `rm -rf .output .tanstack` first, both with and without the preset set.
